# -*- coding: utf-8 -*-
"""Group_9_Platform of online food ordering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gyyYWYyFjO7xLMFIAiAXW94KSoP1yuTf

*GROUP 9:  Pie Chart * Malik, Naseem, Praveen, Manpreet, Hasyashri, Simarjit.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
# %matplotlib inline
import matplotlib.pyplot as plt

df_rank = pd.read_csv('/content/onlinefoods[1].csv')
#df_rank = pd.read_csv('https://www.kaggle.com/datasets/sudarshan24byte/online-food-dataset.csv')
df_rank.head()

#The number of rows in the DataFrame.
#The number of columns in the DataFrame.

df_rank.shape

df_rank.isnull().sum()

df_var = df_rank.groupby('Occupation').size()
df_var

df_var.plot(kind='pie',
                            figsize=(10, 6),
                            autopct='%1.1f%%',
                            startangle=0,
                            shadow=False,
                            labels=None,         # turn off labels on pie chart
                            pctdistance=1.12,    # the ratio between the center of each pie slice and the start of the text generated by autopct
                            )
plt.title('Food ordering online based on Occupation Range', y=1.12, fontsize = 15)
plt.axis('equal')

# add legend
plt.legend(labels=df_var.index, loc='upper left', fontsize=7)

plt.show()

"""This pie chart give the categorial information about people who are at the different occupation. It is clear from the graph that mostly students are involved in ordereing food online which is more than half of the total values."""

df_var = df_rank.groupby('Educational Qualifications').size()
df_var

df_var.plot(kind='pie',
                            figsize=(10, 6),
                            autopct='%1.1f%%',
                            startangle=0,
                            shadow=False,
                            labels=None,         # turn off labels on pie chart
                            pctdistance=1.12,    # the ratio between the center of each pie slice and the start of the text generated by autopct
                            )
plt.title('Food ordering online based on Educational Qualifications', y=1.12, fontsize = 15)
plt.axis('equal')

# add legend
plt.legend(labels=df_var.index, loc='upper left', fontsize=7)

plt.show()

"""This pie chart give the information about the educational qualifications of the people who are ordering food online. It is evident from the graph that Graduates and Post Graduates are majority population preferring ordereing food online. People who are still at school or are busy pursuing PHD are not liking preparing food at home or not online."""

df_education = df_rank.groupby('Occupation').size()
df_education

df_education.plot(kind='pie',
                            figsize=(10, 6),
                            autopct='%1.1f%%',
                            startangle=30,
                            shadow=True,
                            labels=None,         # turn off labels on pie chart
                            pctdistance=1.12,    # the ratio between the center of each pie slice and the start of the text generated by autopct
                            )
plt.title('Food ordering online based on educational qualification', y=1.12, fontsize = 15)
plt.axis('equal')

# add legend
plt.legend(labels=df_education.index, loc='upper left', fontsize=7)

plt.show()

### Online ordering criteria on the basis of FEEDBACK response.
df_feedback = df_rank.groupby('Feedback').size()
df_feedback

df_feedback.plot(kind='pie',
                            figsize=(10, 6),
                            autopct='%1.1f%%',
                            startangle=30,
                            shadow=False,
                            labels=None,         # turn off labels on pie chart
                            pctdistance=1.12,    # the ratio between the center of each pie slice and the start of the text generated by autopct
                            )
plt.title('Ratio of feedback given for online ordering', y=1.12, fontsize = 18)

plt.axis('equal')

# add legend
plt.legend(labels=df_feedback.index, loc='upper left', fontsize=14)

plt.show()

df_famsize = df_rank.groupby('Family size').size()
print("No. of members in the family",df_famsize)

df_famsize.plot(kind='pie',
                            figsize=(10, 6),
                            autopct='%1.1f%%',
                            startangle=30,
                            shadow=True,
                            labels=None,         # turn off labels on pie chart
                            pctdistance=1.12,    # the ratio between the center of each pie slice and the start of the text generated by autopct
                            )
plt.title('family size v/s online ordering', y=1.12, fontsize = 18)
plt.axis('equal')

#df_famsize.sort_values('Family size', ascending=False)
#df_famsize.sort_values(by=['Family size'])

# add legend
plt.legend(labels=df_famsize.index, loc='upper left', fontsize=14)

plt.show()

fig,ax=plt.subplots(figsize=(10, 4))

ax.pie(df_famsize,autopct='%1.1f%%', pctdistance=1.25)

ax.set_aspect('equal')  # Ensure pie is drawn as a circle
labels=df_famsize.index
plt.title('Feedback on Online food ordering')
ax.legend(labels,bbox_to_anchor=(1, 0, 0.5, 1))
plt.show()

"""Displaying the Pie chart using the matplotlilb."""

import plotly.express as px
import plotly.graph_objects as go
fig=go.Figure()
fig
fig = px.pie(df_rank,values=df_rank['Family size'], names='Family size', title='Online ordering trend based on Family Size')
fig.show()

"""Using the Go function with Plotly"""

